### ISSUE TITLE
support for Anchors in `buildUrl` function

### ISSUE THREAD

**Issue by sarangspadalkar** [electrovir/url-vir#2]
## Description
Currently, the `buildUrl` function lacks support for appending an [anchor](https://en.wikipedia.org/wiki/URI_fragment) (#) to the generated URL. 

## Proposed Usage

The proposed enhancement would allow users to specify an anchor parameter in the buildUrl options, resulting in a URL with a hash fragment pointing to the specified anchor.

### Example
Here is an example of the desired usage:
```typescript
const origin = "http://localhost:5000"
const url = buildUrl(origin, {
    paths: ['abc', 'pqr'],
    anchor: {
        anchor1: 'y',
    },
}).href;
```
### Expected Output

`http://localhost:5000/abc/pqr#anchor1=y`

## Additional Context

In some cases, third-party services like Twilio require URLs with anchors for callback requests. For example, Twilio’s webhook configuration allows URL fragments (anchors) to specify connection overrides. You can find more information and examples in the [Twilio Webhooks documentation](https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides#examples).

Let me know if there’s anything I can do to help clarify the requirements or contribute to this enhancement!

**Comment by electrovir** [comment]
Are you referring to the hash? That is supported.

**Comment by sarangspadalkar** [comment]
> Are you referring to the hash? That is supported.

Currently, the `hash` property only accepts a `string` type. However, I would like `hash` to accept an `object` so we can provide key-value pairs for anchor parameters.

For example, to construct a URL like `https://example.com/foo?query=123#ct=1000&rt=1000` (from [Twilio's webhook connection overrides documentation](https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides#examples)):

Current experience: 
```typescript

buildUrl("https://example.com", {
        paths: [
            'foo',
        ],
        search: {
          query: 123
        },
        hash: 'ct=1000&rt=1000',
    }).href;

```

Expected experience: 
```typescript

buildUrl("https://example.com", {
        paths: [
            'foo',
        ],
        search: {
          query: 123,
        },
        hash: {
          ct: 1000,
          rt: 1000
        },
    }).href;

```

**Comment by electrovir** [comment]
Ah, I see what you mean. That is not the appropriate use case for the hash property, it's meant to be used to reference a specific header on a page (for jumping to the header). 

Historically the hash property was used as a replacement for SPA routing in browsers that didn't support the `history` API, but those days are long gone. Twilio's behavior that you mentioned is quite strange.

For the moment I'm going to close this as not planned, because it's not a standard use case for the hash property.
